version: '3'
services:
  envoy:
    build:
      context: ./
      dockerfile: ./docker/envoy/Dockerfile
    ports:
      - 8080:8080
      - 9090:9090
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
