// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package containers

import (
	"spork/config"
	"spork/grpc"
	"spork/postgres"
	"spork/users"
)

// Injectors from init.go:

func InitApp() *App {
	configConfig := config.Default()
	db := postgres.Init(configConfig)
	store := users.NewStore(db)
	service := users.NewService(store)
	server := grpc_api.NewServer(service, store)
	runner := grpc_api.NewRunner(server)
	app := NewApp(runner)
	return app
}
