// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package containers

import (
	"spork/account"
	"spork/config"
	"spork/grpc"
	"spork/postgres"
	"spork/rest"
	"spork/users"
)

// Injectors from init.go:

func InitApp() *App {
	configConfig := config.Default()
	db := postgres.Init(configConfig)
	store := users.NewStore(db)
	service := account.NewService(store)
	grpc_apiUsers := grpc_api.NewUsersServer(service, store)
	files := grpc_api.NewFilesServer()
	runner := grpc_api.NewRunner(grpc_apiUsers, files, configConfig)
	server := rest.NewServer(configConfig, service)
	app := NewApp(runner, server)
	return app
}
