
POST http://localhost:8000/api/account/login HTTP/1.1
content-type: application/json

{
    "Email": "olexiy.tkachenko+3@gmail.com",
    "Password": "testpassword"
}

###
POST http://localhost:8000/api/images/upload
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNTYxMTA2MTM2LCJpYXQiOjE1NTg1MTQxMzZ9.oT9e8jP8T6XnpYPyB1tdArcqv56f3fis7MZRkKGwn_g
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.jpg"
Content-Type: image/jpeg

< ./temp/run.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
GET http://localhost:8000/api/account/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNTYxMTA2MTM2LCJpYXQiOjE1NTg1MTQxMzZ9.oT9e8jP8T6XnpYPyB1tdArcqv56f3fis7MZRkKGwn_g
